name: ScreenshotBot Tests

on:
  pull_request:
    branches:
      - main

jobs:
  screenshotbot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run tests and upload screenshots
        run: |
          npm run test
          screenshotbot upload
